photo/urls.py
from django.urls import path
from . import views

#URLパターンを逆引きできるように名前を付ける
app_name = 'photo'

#URLパターンを登録する変数
urlpatterns = [
    #photoアプリへのアクセスはviewモジュールのIndexViewを実行
    path('', views.IndexView.as_view(), name='index'),
]

photoproject/urls.py
from django.contrib import admin
from django.urls import path, include #include追加

urlpatterns = [
    path('admin/', admin.site.urls),
    
    #photo.urlsへのURLパターン
    path('', include('photo.urls')),
]

photo/models.py
from django.db import models

# Create your models here.

photo/views.py
from django.shortcuts import render

from django.views.generic import TemplateView

class IndexView(TemplateView):

    template_name = 'index.html'

# Create your views here.

photoproject/accounts/templates/signup.html
<!--　ベーステンプレートを適用する-->
{% extends 'base.html'%}
<!--　ヘッダー情報のページタイトルを設定する-->
{% block title %}Sign up{% endblock %}

    {% block contents %}
    <!-- Bootatrapのグリッドシステム-->
    <hr>
    <div class = "container">
        <!--行を配置-->
        <div class = "row">
            <!--列の左右に余白offset-2を入れる-->
            <div class ="col offset-2">
                <h3>サインアップ</h3>
                <!--サインアップのフォームを配置-->
                <form method = "post">
                    {% csrf_token %}
                    <!--formからフィールドを取り出す-->
                    {% for field in form %}
                    <p>
                        <!--ラベルを出力-->
                        {{ field.label_tag}}<br>
                        <!--<input>タグを出力-->
                        {{ field }}
                        <!-- help_textを出力-->
                        {% if field.help_text %}
                        <small style="color: grey">{{ field.help_text }}</small>
                        {% endif %}
                        <!--エラー発生時のテキストerrorsを出力-->
                        {% for error in field.errors %}
                            <p style="color: red">{{ error}}</p>
                        {% endfor %}
                    </p>
                    {% endfor %}
                    <p style="color:red">
                        ※メールアドレスはパスワードをリセットする際に必要になりますので、登録をお願いします。
                    </p>
                    <!--Sign upボタンを出力-->
                    <input type="submit" value="Sign up">
                </form>
                <!--トップページのリンクテキスト-->
                <br>
                <p><a href="{% url 'photo:index' %}">
                    登録をやめてトップページに戻る</a>
                </p>
            </div>
        </div>
    </div>
    {% endlock %}